language: python
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
env:
  - TOX_ENV=py27-pymongo
  - TOX_ENV=py27-pyexecjs
  - TOX_ENV=py33-pymongo
  - TOX_ENV=py33-pyexecjs
  - TOX_ENV=py34-pymongo
  - TOX_ENV=py34-pyexecjs
  - TOX_ENV=pypy-pymongo
  - TOX_ENV=pypy-pyexecjs
  - TOX_ENV=pep8
script:
  - tox -e $TOX_ENV
services:
  - mongodb
install: pip install tox
